export type Session = {
  id: string;
  slug: string;
  title: string;
  subtitle: string;
  duration: string;
  objectives: string[];
  topics: string[];
  build: string[];
  deliverables: string[];
};

export type Track = {
  id: string;
  slug: string;
  name: string;
  shortDescription: string;
  outcomes: string[];
  sessions: Session[];
};

export const tracks: Track[] = [
  {
    id: "robotics-core",
    slug: "robotics-core",
    name: "Robotics Core",
    shortDescription: "Master the fundamentals of robotics and embedded systems. Build real projects from scratch.",
    outcomes: [
      "Complete understanding of Arduino and embedded systems",
      "Hands-on experience with sensors, actuators, and motors",
      "Ability to build integrated robotics projects",
      "Professional portfolio of working prototypes",
    ],
    sessions: [
      {
        id: "session-1",
        slug: "arduino-intro-leds-buttons-buzzer-potentiometer",
        title: "Arduino Intro + LEDs + Buttons + Buzzer + Potentiometer",
        subtitle: "Master the basics of Arduino programming and digital/analog I/O",
        duration: "3 hours",
        objectives: [
          "Understand Arduino platform and IDE",
          "Control digital outputs (LEDs)",
          "Read digital inputs (buttons)",
          "Work with analog inputs (potentiometer)",
          "Generate sound with buzzer",
        ],
        topics: [
          "Arduino hardware overview",
          "Digital vs Analog signals",
          "pinMode, digitalWrite, digitalRead",
          "analogRead and PWM",
          "tone() function for audio",
        ],
        build: [
          "LED blinking patterns",
          "Button-controlled LED",
          "Potentiometer brightness control",
          "Musical buzzer project",
        ],
        deliverables: [
          "Working LED control system",
          "Interactive button project",
          "Analog sensor reading project",
          "Complete code documentation",
        ],
      },
      {
        id: "session-2",
        slug: "ultrasonic-servo-radar-project",
        title: "Ultrasonic + Servo + Radar Project",
        subtitle: "Build a radar system using ultrasonic sensors and servo motors",
        duration: "3 hours",
        objectives: [
          "Master ultrasonic distance sensing",
          "Control servo motors precisely",
          "Integrate sensors with actuators",
          "Create a scanning radar system",
        ],
        topics: [
          "HC-SR04 ultrasonic sensor",
          "Servo motor control (SG90)",
          "Trigonometric calculations",
          "Serial communication for debugging",
          "Radar visualization concepts",
        ],
        build: [
          "Ultrasonic distance meter",
          "Servo-controlled scanning system",
          "Real-time distance display",
          "Radar visualization on serial monitor",
        ],
        deliverables: [
          "Functional radar system",
          "Distance measurement accuracy report",
          "Code with comments",
          "Project demonstration video",
        ],
      },
      {
        id: "session-3",
        slug: "bluetooth-ir-integration",
        title: "Bluetooth + IR Integration",
        subtitle: "Wireless communication and remote control systems",
        duration: "3 hours",
        objectives: [
          "Implement Bluetooth communication",
          "Work with IR sensors and transmitters",
          "Create wireless control systems",
          "Handle multiple communication protocols",
        ],
        topics: [
          "HC-05/HC-06 Bluetooth modules",
          "IR sensors and transmitters",
          "Serial communication protocols",
          "AT commands for Bluetooth",
          "Protocol integration strategies",
        ],
        build: [
          "Bluetooth-controlled LED",
          "IR remote control system",
          "Dual-protocol communication",
          "Wireless sensor data transmission",
        ],
        deliverables: [
          "Bluetooth communication project",
          "IR control system",
          "Integration demonstration",
          "Communication protocol documentation",
        ],
      },
      {
        id: "session-4",
        slug: "bluetooth-car-foundations",
        title: "Bluetooth Car Foundations",
        subtitle: "Build the foundation for a Bluetooth-controlled robot car",
        duration: "3 hours",
        objectives: [
          "Design robot car chassis",
          "Implement motor control basics",
          "Create Bluetooth control interface",
          "Establish movement commands",
        ],
        topics: [
          "Robot car chassis design",
          "DC motor basics",
          "Motor driver introduction",
          "Bluetooth command parsing",
          "Movement algorithms",
        ],
        build: [
          "Car chassis assembly",
          "Basic motor control",
          "Bluetooth command system",
          "Forward/backward/turn movements",
        ],
        deliverables: [
          "Assembled robot car",
          "Basic movement control",
          "Bluetooth interface",
          "Control command documentation",
        ],
      },
      {
        id: "session-5",
        slug: "smart-car-ultrasonic-ir-safety",
        title: "Smart Car: Ultrasonic + IR Safety Layer",
        subtitle: "Add obstacle avoidance and safety features to your robot car",
        duration: "3 hours",
        objectives: [
          "Implement obstacle detection",
          "Create safety protocols",
          "Integrate multiple sensors",
          "Build autonomous safety behaviors",
        ],
        topics: [
          "Multi-sensor integration",
          "Obstacle avoidance algorithms",
          "Priority-based decision making",
          "Safety layer architecture",
          "Sensor fusion concepts",
        ],
        build: [
          "Ultrasonic obstacle detection",
          "IR line following integration",
          "Automatic stop on obstacle",
          "Safe navigation system",
        ],
        deliverables: [
          "Smart car with safety features",
          "Obstacle avoidance system",
          "Safety protocol documentation",
          "Integration test results",
        ],
      },
      {
        id: "session-6",
        slug: "power-engineering-buck-converter",
        title: "Power Engineering: Buck Converter + Safe Wiring",
        subtitle: "Master power management and safe electrical practices",
        duration: "3 hours",
        objectives: [
          "Understand power requirements",
          "Implement buck converters",
          "Design safe power distribution",
          "Protect circuits from damage",
        ],
        topics: [
          "Voltage regulation basics",
          "Buck converter operation",
          "Power calculation and sizing",
          "Safe wiring practices",
          "Circuit protection methods",
        ],
        build: [
          "Buck converter circuit",
          "Power distribution system",
          "Voltage monitoring system",
          "Protected power supply",
        ],
        deliverables: [
          "Working power system",
          "Power calculation report",
          "Safety documentation",
          "Circuit protection implementation",
        ],
      },
      {
        id: "session-7",
        slug: "mpu6050-fundamentals",
        title: "MPU6050 Fundamentals + Applications",
        subtitle: "Master motion sensing with accelerometer and gyroscope",
        duration: "3 hours",
        objectives: [
          "Understand IMU sensors",
          "Read accelerometer data",
          "Read gyroscope data",
          "Calculate orientation and motion",
        ],
        topics: [
          "MPU6050 sensor overview",
          "I2C communication protocol",
          "Accelerometer principles",
          "Gyroscope principles",
          "Sensor fusion basics",
        ],
        build: [
          "MPU6050 data reading",
          "Motion detection system",
          "Orientation calculation",
          "Gesture recognition basics",
        ],
        deliverables: [
          "MPU6050 integration project",
          "Motion sensing system",
          "Data analysis report",
          "Application examples",
        ],
      },
      {
        id: "session-8",
        slug: "oled-lcd-joystick-ui",
        title: "OLED/LCD + Joystick UI (Menu + Dashboard)",
        subtitle: "Create user interfaces with displays and input controls",
        duration: "3 hours",
        objectives: [
          "Work with OLED and LCD displays",
          "Implement joystick control",
          "Design menu systems",
          "Create interactive dashboards",
        ],
        topics: [
          "OLED display (SSD1306)",
          "LCD display basics",
          "Joystick input reading",
          "Menu system architecture",
          "UI state management",
        ],
        build: [
          "Display text and graphics",
          "Joystick-controlled menu",
          "Interactive dashboard",
          "Multi-screen navigation",
        ],
        deliverables: [
          "Working display system",
          "Menu interface",
          "Dashboard project",
          "UI documentation",
        ],
      },
      {
        id: "session-9",
        slug: "rtc-7seg-max7219",
        title: "RTC + 7-seg (TM1637) + MAX7219 Basics",
        subtitle: "Time management and advanced display systems",
        duration: "3 hours",
        objectives: [
          "Implement real-time clock",
          "Control 7-segment displays",
          "Work with MAX7219 matrix",
          "Create time-based systems",
        ],
        topics: [
          "DS1307/DS3231 RTC modules",
          "TM1637 7-segment displays",
          "MAX7219 LED matrix",
          "SPI communication",
          "Time-based programming",
        ],
        build: [
          "RTC time display",
          "7-segment clock",
          "MAX7219 matrix patterns",
          "Time-based automation",
        ],
        deliverables: [
          "RTC integration project",
          "Display system",
          "Time-based application",
          "Documentation",
        ],
      },
      {
        id: "session-10",
        slug: "dc-motors-drivers-mastery",
        title: "DC Motors Drivers Mastery: L298N vs L293D (PWM + Ramps)",
        subtitle: "Master motor control with professional driver modules",
        duration: "3 hours",
        objectives: [
          "Compare L298N and L293D",
          "Implement PWM speed control",
          "Create smooth acceleration ramps",
          "Control multiple motors",
        ],
        topics: [
          "L298N driver module",
          "L293D driver module",
          "PWM speed control",
          "Acceleration/deceleration ramps",
          "Motor control algorithms",
        ],
        build: [
          "L298N motor control",
          "L293D motor control",
          "PWM speed variation",
          "Smooth acceleration system",
        ],
        deliverables: [
          "Motor control comparison",
          "PWM implementation",
          "Ramp control system",
          "Performance analysis",
        ],
      },
      {
        id: "session-11",
        slug: "stepper-motors-nema-a4988",
        title: "Stepper Motors: NEMA + A4988 (Step/Dir + Microstepping Concept)",
        subtitle: "Precision motion control with stepper motors",
        duration: "3 hours",
        objectives: [
          "Understand stepper motor principles",
          "Control NEMA steppers",
          "Use A4988 driver",
          "Implement microstepping",
        ],
        topics: [
          "Stepper motor basics",
          "NEMA motor specifications",
          "A4988 driver module",
          "Step/direction control",
          "Microstepping concepts",
        ],
        build: [
          "Basic stepper control",
          "Precise positioning",
          "Microstepping implementation",
          "Multi-axis control",
        ],
        deliverables: [
          "Stepper motor project",
          "Precision positioning system",
          "Microstepping demonstration",
          "Control algorithm documentation",
        ],
      },
      {
        id: "session-12",
        slug: "capstone-integrated-robotics",
        title: "Capstone Integrated Robotics System",
        subtitle: "Build a complete robotics system integrating all learned concepts",
        duration: "3 hours",
        objectives: [
          "Integrate all previous concepts",
          "Design complete system architecture",
          "Implement complex behaviors",
          "Create portfolio-ready project",
        ],
        topics: [
          "System architecture design",
          "Multi-sensor integration",
          "Complex control algorithms",
          "Project documentation",
          "Testing and optimization",
        ],
        build: [
          "Complete robotics system",
          "Multi-function robot",
          "Advanced control system",
          "Professional documentation",
        ],
        deliverables: [
          "Complete robotics project",
          "System documentation",
          "Demo video",
          "Portfolio presentation",
        ],
      },
    ],
  },
  {
    id: "robotics-ai",
    slug: "robotics-ai",
    name: "Robotics + AI",
    shortDescription: "Extend your robotics skills with AI and computer vision. Add intelligence to your robots.",
    outcomes: [
      "Python programming for robotics",
      "Computer vision implementation",
      "AI integration with hardware",
      "Intelligent robot systems",
    ],
    sessions: [
      {
        id: "session-13",
        slug: "python-foundations-engineers",
        title: "Python Foundations for Engineers",
        subtitle: "Learn Python programming specifically for robotics and engineering applications",
        duration: "3 hours",
        objectives: [
          "Master Python syntax and basics",
          "Work with libraries for robotics",
          "Understand data structures",
          "Implement algorithms in Python",
        ],
        topics: [
          "Python basics and syntax",
          "Data types and structures",
          "Functions and modules",
          "File I/O operations",
          "Robotics-specific libraries",
        ],
        build: [
          "Python programming exercises",
          "Library integration",
          "Data processing scripts",
          "Basic automation scripts",
        ],
        deliverables: [
          "Python proficiency",
          "Working scripts",
          "Library documentation",
          "Code examples",
        ],
      },
      {
        id: "session-14",
        slug: "opencv-fundamentals",
        title: "OpenCV Fundamentals (Image/Video Basics)",
        subtitle: "Master computer vision with OpenCV library",
        duration: "3 hours",
        objectives: [
          "Understand image processing",
          "Work with OpenCV library",
          "Process images and video",
          "Implement basic CV operations",
        ],
        topics: [
          "OpenCV installation and setup",
          "Image loading and manipulation",
          "Video capture and processing",
          "Basic image operations",
          "Color space conversions",
        ],
        build: [
          "Image processing scripts",
          "Video capture system",
          "Basic CV operations",
          "Image transformation project",
        ],
        deliverables: [
          "OpenCV integration",
          "Image processing project",
          "Video processing system",
          "CV fundamentals documentation",
        ],
      },
      {
        id: "session-15",
        slug: "computer-vision-mini-projects",
        title: "Computer Vision Mini-Projects (Line Detection, Motion Detection)",
        subtitle: "Build practical CV projects for robotics applications",
        duration: "3 hours",
        objectives: [
          "Implement line detection",
          "Create motion detection system",
          "Apply CV to robotics",
          "Build practical applications",
        ],
        topics: [
          "Edge detection algorithms",
          "Line detection (Hough transform)",
          "Motion detection techniques",
          "Object tracking basics",
          "CV-robotics integration",
        ],
        build: [
          "Line detection system",
          "Motion detection application",
          "Object tracking project",
          "CV-robotics integration",
        ],
        deliverables: [
          "Line detection project",
          "Motion detection system",
          "Integration demonstration",
          "Project documentation",
        ],
      },
      {
        id: "session-16",
        slug: "cv-robotics-integration",
        title: "CV + Robotics Integration Concept (Camera Triggers Actions, Sending Commands)",
        subtitle: "Integrate computer vision with robotics hardware",
        duration: "3 hours",
        objectives: [
          "Connect camera to robotics system",
          "Process visual input",
          "Trigger actions based on vision",
          "Create intelligent behaviors",
        ],
        topics: [
          "Camera integration",
          "Vision-based decision making",
          "Command generation from CV",
          "Real-time processing",
          "System integration architecture",
        ],
        build: [
          "Camera-robot connection",
          "Vision-based control",
          "Action triggering system",
          "Complete CV-robotics system",
        ],
        deliverables: [
          "Integrated CV-robotics system",
          "Vision-based control",
          "Integration documentation",
          "Demo video",
        ],
      },
    ],
  },
  {
    id: "full-system",
    slug: "full-system",
    name: "Full System",
    shortDescription: "Complete system with Raspberry Pi, web control, and advanced robotics. Build the SPY-DER project.",
    outcomes: [
      "Raspberry Pi development",
      "Web-based robot control",
      "Camera streaming and control",
      "Complete integrated system",
    ],
    sessions: [
      {
        id: "session-17",
        slug: "raspberry-pi-zero-setup-camera",
        title: "Raspberry Pi Zero Setup + Camera",
        subtitle: "Set up Raspberry Pi and integrate camera for robotics",
        duration: "3 hours",
        objectives: [
          "Set up Raspberry Pi Zero",
          "Install and configure OS",
          "Integrate camera module",
          "Establish communication",
        ],
        topics: [
          "Raspberry Pi Zero overview",
          "OS installation (Raspbian)",
          "Camera module setup",
          "SSH and remote access",
          "GPIO basics",
        ],
        build: [
          "Raspberry Pi setup",
          "Camera integration",
          "Basic camera capture",
          "Remote access system",
        ],
        deliverables: [
          "Working Raspberry Pi",
          "Camera integration",
          "Remote access setup",
          "Setup documentation",
        ],
      },
      {
        id: "session-18",
        slug: "flask-web-control-dashboard",
        title: "Flask Web Control Dashboard",
        subtitle: "Build a web-based control interface for your robot",
        duration: "3 hours",
        objectives: [
          "Create Flask web application",
          "Design control dashboard",
          "Implement robot control API",
          "Build responsive interface",
        ],
        topics: [
          "Flask framework basics",
          "Web API design",
          "Frontend-backend communication",
          "Dashboard UI design",
          "Real-time control",
        ],
        build: [
          "Flask web server",
          "Control dashboard",
          "Robot control API",
          "Web interface",
        ],
        deliverables: [
          "Working web dashboard",
          "Control API",
          "Web interface",
          "API documentation",
        ],
      },
      {
        id: "session-19",
        slug: "streaming-snapshots-access-token",
        title: "Streaming/Snapshots + Basic Access Token",
        subtitle: "Implement camera streaming and secure access",
        duration: "3 hours",
        objectives: [
          "Stream camera feed",
          "Capture snapshots",
          "Implement authentication",
          "Secure web access",
        ],
        topics: [
          "Camera streaming (MJPG)",
          "Snapshot capture",
          "Access token authentication",
          "Security best practices",
          "Web streaming protocols",
        ],
        build: [
          "Camera streaming system",
          "Snapshot functionality",
          "Authentication system",
          "Secure web access",
        ],
        deliverables: [
          "Streaming system",
          "Snapshot system",
          "Authentication implementation",
          "Security documentation",
        ],
      },
      {
        id: "session-20",
        slug: "spy-der-capstone",
        title: "SPY-DER Capstone (Web + Camera + Movement Modes)",
        subtitle: "Build the complete SPY-DER robot with web control and camera",
        duration: "3 hours",
        objectives: [
          "Integrate all components",
          "Create complete system",
          "Implement movement modes",
          "Build portfolio project",
        ],
        topics: [
          "System integration",
          "Web-robot communication",
          "Movement mode programming",
          "Camera integration",
          "Complete system architecture",
        ],
        build: [
          "Complete SPY-DER system",
          "Web control interface",
          "Camera streaming",
          "Multiple movement modes",
        ],
        deliverables: [
          "Complete SPY-DER project",
          "System documentation",
          "Demo video",
          "Portfolio presentation",
        ],
      },
    ],
  },
];

